imcs rpm pull request
cfpb/imcs-el6-rpm pull request #1
Opened 2016-01-14 15:53 UTC by olivermel

2016-01-14 16:03 UTC, Scotchester commented
Same comment as cfpb/pg_jobmon#1 :)

2016-01-20 15:43 UTC, tanderegg commented
Hi @olivermel - a couple last things

- [ ] Remove the .vagrant folder from your repo by running "git rm --cached .vagrant" and then commit and push
- [ ] Add the line ".vagrant" to your .gitignore file, this will prevent git from adding this folder back into the repo
- [ ] Add a variable to the imcs.spec file for the file path, like "%define pg_dir /usr/pgsql-9.4", and substitute the variable for all occurrances of that path
- [ ] Update the documentation to indicate that the path can be changed when the rpmbuild command is run, like: "rpmbuild -ba imcs.spec --define 'pg_dir /usr/my_pgsql'", which will allow us to customize the install location according to where postgres is located.
- [ ] Remove the Build Requires line, as this only works with regular postgres94-devel, which we won't have.

Thanks!

2016-01-29 16:34 UTC, tanderegg commented
@olivermel There's still a few issues unresolved up above, plus a few more I found:

- [ ] When the bootstrap script downloads the source file, it is named "master.tar.gz", but the spec file is looking for "imcs-1.06.tar.gz" when it tries to decompress

- [ ] The yum package "libicu-devel" should be installed by the bootstrap script.

- [ ] Unfortunately, it seems like one cannot override "defines" from the command line, so we will have to remove the "define pg_dir" line from the SPEC file, and note in the documentation that this variable must be passed from the command line when rpmbuild is run.

- [ ] I needed change the "%make_install" line to "make install USE_PGXS=1 DESTDIR=${RPM_BUILD_ROOT}" for it to find all the files and place them in the right place.

- [ ] Make a note in the documentation that "pg_config" must be accessible from the user's path.

2016-02-01 18:55 UTC, tanderegg commented on SPECS/imcs.spec
> +%files
@olivermel Looks like the files section disappeared?

2016-02-01 18:56 UTC, tanderegg commented on SPECS/imcs.spec
> +%install
I think this line "%install" needs to go above the "make install" line

2016-02-01 18:56 UTC, tanderegg commented on README.md
> +    4. Run "rpmbuild -ba SPECS/imcs.spec" to build the imcs rpm package.
Please indicate the "--define 'pg_dir /whatever'" needs to be included

2016-02-01 18:56 UTC, tanderegg commented on README.md
> +      rpmbuild -ba /SPECS/imcs.spec
ditto

2016-09-22 20:08 UTC, tanderegg commented on SPECS/imcs.spec
> +/etc/profile.d/imcs.sh
@olivermel This file is no longer needed, but none of the actual extension files are here.  I believe they are:

```
%{pg_dir}/lib/imcs.so
%{pg_dir}/share/extension/imcs--1.1.sql
%{pg_dir}/share/extension/imcs.control
```

2016-09-22 20:10 UTC, tanderegg commented on bootstrap.sh
> +sudo yum -y install postgresql95-server postgresql95 postgresql95-devel.x86_64
@olivermel postgresql95-server is not needed to build the package, so let's remove that.

2016-09-22 20:11 UTC, tanderegg requested changes

2016-09-22 20:11 UTC, tanderegg commented on .vagrant/machines/imcs/virtualbox/action_provision
> +1.5:87b3f301-8382-4277-ab67-7e864df4a869
@olivermel Please remove all files in ".vagrant", these should never be in the repository.

2016-09-22 20:11 UTC, tanderegg commented on .gitignore
> +bootstrap.sh-mine
@olivermel Also remove the boostrap.sh-mine line, it's fine to use that during development but shouldn't be part of the final product.

2016-09-22 20:11 UTC, tanderegg commented on INSTALL.md
> +4. Run rpmbuild -ba SPECS/imcs.spec 'pg_dir /usr/pgsql-9.4' to build the imcs rpm package.
This should be:
`rpmbuild -ba SPECS/imcs.spec --define 'pg_dir /usr/pgsql-9.5' --define '_suffix 95'

2016-09-22 20:11 UTC, tanderegg commented on SPECS/imcs.spec
> +mkdir -p %{buildroot}/etc/profile.d
@olivermel We don't need to add these settings to the path _after_ imcs has been installed, so we don't need the imcs.sh file in the package.  It can be assumed that Postgres is setup properly.

2016-09-22 20:11 UTC, tanderegg commented on bootstrap.sh
> +sudo yum -y install vim tree
@olivermel vim and tree are not required to build the package, so please remove them from here.

2016-09-22 20:11 UTC, tanderegg commented on SPECS/imcs.spec
> +Name:    	imcs%{suffix}
@olivermel Apparently it must be `_suffix` instead of `suffix` for some dumb reason ;)  Maybe `suffix` is a reserved word in rpmbuild or something?

2016-09-22 20:11 UTC, tanderegg commented on INSTALL.md
> +3. Run rpmbuild -ba /SPECS/imcs.spec 'pg_dir /usr/pgsql-9.4'
Same changes here

2016-09-22 20:11 UTC, tanderegg commented on INSTALL.md
> +Install the built RPM by running "sudo yum install RPMS/x86_64/imcs-1.06-1.el6.x86_64.rpm"
imcs95-1.06...

2016-09-22 20:11 UTC, tanderegg commented on README.md
> +    4. Run rpmbuild -ba SPECS/imcs.spec --define 'pg_dir /usr/pgsql-9.5' --define 'suffix 95'  to build the imcs rpm package.
_suffix

2016-09-22 20:11 UTC, tanderegg commented on README.md
> +      rpmbuild -ba /SPECS/imcs.spec  --define 'pg_dir /usr/pgsql-9.5' --define 'suffix 95'
_suffix

2016-09-22 20:11 UTC, tanderegg commented on SPECS/imcs.spec
> +Obsoletes: 	imcs%{suffix} <= 1.05
_suffix

2016-09-22 20:11 UTC, tanderegg commented on SPECS/imcs.spec
> +Provides: 	imcs%{suffix} = 1.06
_suffix

2016-09-22 20:47 UTC, tanderegg commented on SPECS/imcs.spec
> +#Source:  	https://github.com/knizhnik/imcs/archive/master.tar.gz
Remove the commented out line, please.

2016-09-26 17:25 UTC, tanderegg commented on .vagrant/machines/imcs/virtualbox/action_provision
> +1.5:87b3f301-8382-4277-ab67-7e864df4a869
@olivermel - Still need to remove these .vagrant/* files.  You can remove these from the repository (without deleting them on your machine), but running this command:
```
git rm --cached -r .vagrant
```

2016-09-26 17:27 UTC, tanderegg commented on SPECS/imcs.spec
> +#make
@olivermel Doesn't `make` still need to be run before `make install`, or was that not necessary to produce the extension files?

2016-09-26 17:27 UTC, tanderegg commented on SPECS/imcs.spec
> +echo $PWD
@olivermel Can you remove this line, since I'm assuming it was here for debugging?

2017-06-19 13:57 UTC, merged